---
lucky-word: Irish
---
spring:
  profiles: subject
words: I,You,He,She,It
lucky-word: Irish13
application
  name: subject 
  
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought
application
  name: verb

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog

