---
lucky-word: Irish
---
spring:
  profiles: subject
  application:
    name: subject 
lucky-word: I,You,He,She,It


  
---
spring:
  profiles: verb
  application:
    name: verb
lucky-word: ran,knew,had,saw,bought


---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
lucky-word: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
lucky-word: boat,book,vote,seat,backpack,partition,groundhog

